---
title: "Bracket"
author: "Andrew Couch"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Packages
library(tidyverse)
library(elo)
library(tidymodels)

# Read in sim
df <- read_rds("ncaa_sim.RDS")

df <- df %>% 
  unnest(sim) %>% 
  select(trials, history) %>% 
  unnest(history)

# Compute head to head matchups
bracket_df <- df %>% 
  select(trials, round, team, opp, team_outcome = outcome) %>% 
  mutate(team_a = if_else(team > opp, team, opp),
         team_b = if_else(team > opp, opp, team),
         opp_outcome = if_else(team_outcome == 1, 0, 1),
         outcome = if_else(team > opp, team_outcome, opp_outcome)) %>% 
  select(trials, round, team_a, team_b, outcome) %>% 
  group_by(team_a, team_b) %>% 
  summarise(avg = mean(outcome)) %>% 
  ungroup() %>% 
  mutate(outcome = if_else(avg >= 0.5, 1, 0)) %>% 
  select(team_a, team_b, outcome)
```

```{r}
# Create bracket
west_df <- tibble(div = "west",
                  team = c("Gonzaga", "Georgia State",
                           "Boise State", "Memphis",
                           "UConn", "New Mexico State",
                           "Arkansas", "Vermont",
                           "Alabama", "Rutgers",
                           "Texas Tech", "Montana State",
                           "Michigan State", "Davidson",
                           "Duke", "CSU Fullerton"))

east_df <- tibble(div = "east",
                  team = c("Baylor", "Norfolk State",
                           "North Carolina", "Marquette",
                           "Saint Mary's", "Indiana",
                           "UCLA", "Akron",
                           "Texas", "Virginia Tech",
                           "Purdue", "Yale",
                           "Murray State", "San Francisco",
                           "Kentucky", "Saint Peter's"))

south_df <- tibble(div = "south",
                   team = c("Arizona", "Bryant", 
                            "Seton Hall", "TCU",
                            "UAB", "Houston",
                            "Illinois", "Chattanooga", 
                            "Colorado State", "Michigan", 
                            "Tennessee", "Longwood", 
                            "Ohio State", "Loyola Chicago",
                            "Villanova", "Delaware"))

midwest_df <- tibble(div = "mdiwest",
                     team = c( "Kansas", "Texas Southern",
                               "San Diego State", "Creighton",
                               "Iowa", "Richmond",
                               "Providence", "South Dakota State",
                               "LSU", "Iowa State",
                               "Wisconsin", "Colgate",
                               "USC", "Miami",
                               "Auburn", "Jacksonville State"))

# Use simulation to get expected outcomes of each round
bind_rows(west_df, east_df, midwest_df, south_df) %>% 
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         round = 1) %>% 
  arrange(game, team) %>% 
  mutate(type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(div, round, game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team) %>% 
  print() %>%
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team) %>% 
  print() %>%
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team) %>% 
  print() %>%
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team) %>% 
  print() %>%
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team) %>% 
  print() %>%
  mutate(game = rep(c(1, 0), n() / 2),
         game = cumsum(game),
         type = rep(c("team_1", "team_2"), n() / 2)) %>% 
  pivot_wider(names_from = type, values_from = team) %>% 
  mutate(team_a = if_else(`team_1` > `team_2`, `team_1`, `team_2`),
         team_b = if_else(`team_1` > `team_2`, `team_2`, `team_1`)) %>% 
  select(game, team_a, team_b) %>% 
  left_join(bracket_df, by = c("team_a", "team_b")) %>% 
  mutate(team = if_else(outcome == 1, team_a, team_b)) %>% 
  select(team)
```


```{r}
# Read in past season scores for tie-breaker
scores <-  tibble(files = list.files(path = "Data")) %>% 
  mutate(files = paste0("Data/", files),
         data = map(files, read_csv, show_col_types = FALSE)) %>% 
  unnest(data) %>% 
  select(date, game_id, files, opponent, team_score, opp_score) %>% 
  distinct() %>% 
  mutate(files = str_replace(files, "_schedule.csv", ""),
         files = str_replace(files, "Data\\/", "")) %>% 
  distinct() %>% 
  rename(team = files, opp = opponent) %>% 
  mutate(across(c(team, opp), 
                .fns = ~str_replace_all(.x, "_|-", " ") %>% 
                  str_replace("St ", "State ")),
         across(c(team, opp),
                .fns = ~case_when(
                  .x == "State Peter's" ~ "Saint Peter's",
                  .x == "Abil Christian" ~ "Abilene Christian",
                  .x == "G Washington" ~ "George Washington",
                  .x == "San José State" ~ "San Jose State",
                  .x == "Jacksonville St" ~ "Jacksonville State",
                  str_starts(.x, "State ") ~ str_replace(.x, "State ", "Saint "),
                  T ~ .x
                ))) 

# Compute median points scored for finalists
bind_rows(
  scores %>% 
    filter(team == "Gonzaga" | team == "Arizona") %>% 
    select(team, team_score),
  scores %>% 
    filter(opp == "Gonzaga" | opp == "Arizona") %>% 
    select(opp, opp_score) %>% 
    rename(team = opp, team_score = opp_score)
) %>% 
  group_by(team) %>% 
  summarise(median = median(team_score, na.rm = TRUE))
```

