---
title: "ELO Adjustment"
author: "Andrew Couch"
date: "3/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(elo)

# Read in NCAA basketball season history 
df <- tibble(files = list.files(path = "Data")) %>% 
  mutate(files = paste0("Data/", files),
         data = map(files, read_csv, show_col_types = FALSE)) %>% 
  unnest(data)

# Clean team names 
df <- df %>% 
  select(date, game_id, files, opponent, team_score, opp_score) %>% 
  distinct() %>% 
  mutate(files = str_replace(files, "_schedule.csv", ""),
         files = str_replace(files, "Data\\/", "")) %>% 
  distinct() %>% 
  rename(team = files, opp = opponent) %>% 
  mutate(across(c(team, opp), 
                .fns = ~str_replace_all(.x, "_|-", " ") %>% 
                  str_replace("St ", "State ")),
         across(c(team, opp),
                .fns = ~case_when(
                  .x == "State Peter's" ~ "Saint Peter's",
                  .x == "Abil Christian" ~ "Abilene Christian",
                  .x == "G Washington" ~ "George Washington",
                  .x == "San José State" ~ "San Jose State",
                  str_starts(.x, "State ") ~ str_replace(.x, "State ", "Saint "),
                  T ~ .x
                ))) 
```


```{r}
match_df <- df %>% 
  group_by(game_id) %>% 
  slice_sample(n = 1) %>% 
  ungroup() %>% 
  arrange(date)

teams <- match_df %>% 
  select(team, opp) %>% 
  pivot_longer(everything()) %>% 
  select(value) %>% 
  distinct() %>% 
  arrange(value) %>% 
  pull(value)

tune_elo <- function(x){
  elo.run(score(team_score, opp_score) ~ team + opp, 
          data = match_df, 
          k = 20,
          initial.elos = set_names(x, teams)) %>% 
    summary() %>% 
    pluck("auc", 1) * -1 
}

end_elo <- elo.run(score(team_score, opp_score) ~ team + opp, 
                   data = match_df, 
                   k = 20) %>% 
  final.elos() %>% 
  as_tibble(rownames = "team") %>% 
  arrange(team) %>% 
  pull(value)

res <- optim(end_elo, tune_elo, method = "L-BFGS-B", lower = 1300, upper = 1750, control = list(maxit = 1e5))
```


```{r}
elo.run(score(team_score, opp_score) ~ team + opp, 
        data = match_df, 
        k = 20) %>% 
  final.elos() %>% 
  as_tibble() %>% 
  summarise(mean = mean(value),
            sd = sd(value))






```


```{r}
tune_elo <- function(x){
  
  mu <- 1500	
  sd_var <-  54.06961	
  
  elo.run(score(team_score, opp_score) ~ team + opp, 
          data = match_df, 
          k = 20,
          initial.elos = set_names((x * sd_var) + mu , teams)) %>% 
    summary() %>% 
    pluck("auc", 1) * -1 
}


res <- optim(rep(0, 759), tune_elo, method = "L-BFGS-B", lower = -2, upper = 2, control = list(maxit = 1e5))
```


```{r}
elo.run(score(team_score, opp_score) ~ team + opp, 
        data = match_df, 
        k = 20) %>% 
  summary() %>% 
  pluck("auc", 1)


elo.run(score(team_score, opp_score) ~ team + opp, 
        data = match_df, 
        k = 20,
        initial.elos = set_names((res$par* 54.06961) + 1500, teams)) %>% 
  summary() %>% 
  pluck("auc", 1)
```


```{r}
elo.run(score(team_score, opp_score) ~ team + opp, 
        data = match_df, 
        k = 20,
        initial.elos = set_names((res$par* 54.06961) + 1500, teams)) %>% 
  final.elos() %>% 
  as_tibble(rownames = "team") %>% 
  rename(adjusted = value) %>% 
  left_join(
    elo.run(score(team_score, opp_score) ~ team + opp, 
            data = match_df, 
            k = 20) %>% 
      final.elos() %>% 
      as_tibble(rownames = "team") %>% 
      rename(original = value),
    by = "team"
  ) %>% 
  ggplot(aes(x = original, y = adjusted)) + 
  geom_abline() + 
  geom_point() + 
  tune::coord_obs_pred()
```


```{r}
elo.run(score(team_score, opp_score) ~ team + opp, 
        data = match_df, 
        k = 20,
        initial.elos = set_names((res$par* 54.06961) + 1500, teams)) %>% 
  final.elos() %>% 
  as_tibble(rownames = "team") %>% 
  write_csv("team_adjustment.csv")
``` 

